#!/bin/bash
#SBATCH --time=00:20:00
#SBATCH --nodes=1 --ntasks-per-node=8  --gpus-per-node=1
#SBATCH --job-name=partialGPUjob
#SBATCH --account=PAS2136
#SBATCH -e gpu.batch-%j.err ###%j will be replaced by the SLURM_JOB_ID
#SBATCH -o gpu.batch-%j.out

cd $SLURM_SUBMIT_DIR

#Load cuda module for Nvidia libraries
module load cuda

#load miniconda3 and activate the environment
module load miniconda3
source activate gen_metadata_train

#output goes to the slurm job output file
echo -e "This is a partial node GPU job:"
scontrol show node $SLURMD_NODENAME

#Run 
python train_model_TT.py config/config/config_training.json
